replicaCount: 2

image:
  repository: ghcr.io/akashfrancis3211/ecommerce-api
  pullPolicy: IfNotPresent
  tag: "a5aad2fe0b214d6cc806748deb4100647be36bc3"

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

containerPort: 8000

readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 15
  periodSeconds: 20

ingress:
  enabled: false
  className: nginx
  host: ecommerce.local
