replicaCount: 2

image:
  repository: ecommerce-api
  pullPolicy: IfNotPresent
  tag: "13"

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

containerPort: 8000

readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 15
  periodSeconds: 20
