replicaCount: 2

image:
  repository: ghcr.io/akashfrancis3211/ecommerce-api
  pullPolicy: IfNotPresent
  tag: "a5aad2fe0b214d6cc806748deb4100647be36bc3"

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

containerPort: 8000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
env:
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: ecommerce-api-secret
        key: DATABASE_URL
        optional: false

readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 15
  periodSeconds: 20

ingress:
  enabled: false
  className: nginx
  host: ecommerce.local
